# Generated by Django 4.1.1 on 2022-09-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subfolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='')),
                ('file_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.folder')),
            ],
        ),
    ]
