# Generated by Django 4.1.1 on 2022-09-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='subfolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.folder'),
        ),
    ]
