# Generated by Django 4.1.1 on 2022-09-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_alter_folder_subfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.folder'),
        ),
    ]
