# Generated by Django 4.1.1 on 2022-09-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_alter_file_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_path',
            new_name='parent_path',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='subfolder',
            new_name='parent_folder',
        ),
    ]
